
  ## Exceptions
  
  try {
    // code
  } catch (ex) {
	throw("My Error" + ex.description)
  } finally {
    // code
  }
  