
  ## Try Catch
  
  try {
    # Code Here!
  } catch (ExceptionName  ex) {
    # Code Here!
  } finally {
    # Code Here!
  }